// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: chat.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Protobufs.chat {
  public static partial class ChatService
  {
    static readonly string __ServiceName = "chat.ChatService";

    static readonly grpc::Marshaller<global::Protobufs.chat.TalkRequest> __Marshaller_chat_TalkRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Protobufs.chat.TalkRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Protobufs.chat.TalkResponse> __Marshaller_chat_TalkResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Protobufs.chat.TalkResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Protobufs.chat.ListenRequest> __Marshaller_chat_ListenRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Protobufs.chat.ListenRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Protobufs.chat.ListenResponse> __Marshaller_chat_ListenResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Protobufs.chat.ListenResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Protobufs.chat.TalkRequest, global::Protobufs.chat.TalkResponse> __Method_Talk = new grpc::Method<global::Protobufs.chat.TalkRequest, global::Protobufs.chat.TalkResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Talk",
        __Marshaller_chat_TalkRequest,
        __Marshaller_chat_TalkResponse);

    static readonly grpc::Method<global::Protobufs.chat.ListenRequest, global::Protobufs.chat.ListenResponse> __Method_Listen = new grpc::Method<global::Protobufs.chat.ListenRequest, global::Protobufs.chat.ListenResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "Listen",
        __Marshaller_chat_ListenRequest,
        __Marshaller_chat_ListenResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Protobufs.chat.ChatReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ChatService</summary>
    [grpc::BindServiceMethod(typeof(ChatService), "BindService")]
    public abstract partial class ChatServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Protobufs.chat.TalkResponse> Talk(global::Protobufs.chat.TalkRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task Listen(global::Protobufs.chat.ListenRequest request, grpc::IServerStreamWriter<global::Protobufs.chat.ListenResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ChatService</summary>
    public partial class ChatServiceClient : grpc::ClientBase<ChatServiceClient>
    {
      /// <summary>Creates a new client for ChatService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ChatServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ChatService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ChatServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ChatServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ChatServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Protobufs.chat.TalkResponse Talk(global::Protobufs.chat.TalkRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Talk(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Protobufs.chat.TalkResponse Talk(global::Protobufs.chat.TalkRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Talk, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Protobufs.chat.TalkResponse> TalkAsync(global::Protobufs.chat.TalkRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TalkAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Protobufs.chat.TalkResponse> TalkAsync(global::Protobufs.chat.TalkRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Talk, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::Protobufs.chat.ListenResponse> Listen(global::Protobufs.chat.ListenRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Listen(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Protobufs.chat.ListenResponse> Listen(global::Protobufs.chat.ListenRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_Listen, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ChatServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ChatServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ChatServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Talk, serviceImpl.Talk)
          .AddMethod(__Method_Listen, serviceImpl.Listen).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ChatServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Talk, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Protobufs.chat.TalkRequest, global::Protobufs.chat.TalkResponse>(serviceImpl.Talk));
      serviceBinder.AddMethod(__Method_Listen, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Protobufs.chat.ListenRequest, global::Protobufs.chat.ListenResponse>(serviceImpl.Listen));
    }

  }
}
#endregion
