// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: helloworld.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Protobufs.helloWorld {
  public static partial class HelloWorldService
  {
    static readonly string __ServiceName = "helloWorld.HelloWorldService";

    static readonly grpc::Marshaller<global::Protobufs.helloWorld.HelloWorldRequest> __Marshaller_helloWorld_HelloWorldRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Protobufs.helloWorld.HelloWorldRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Protobufs.helloWorld.HelloWorldResponse> __Marshaller_helloWorld_HelloWorldResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Protobufs.helloWorld.HelloWorldResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Protobufs.helloWorld.HelloWorldRequest, global::Protobufs.helloWorld.HelloWorldResponse> __Method_Say = new grpc::Method<global::Protobufs.helloWorld.HelloWorldRequest, global::Protobufs.helloWorld.HelloWorldResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Say",
        __Marshaller_helloWorld_HelloWorldRequest,
        __Marshaller_helloWorld_HelloWorldResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Protobufs.helloWorld.HelloworldReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of HelloWorldService</summary>
    [grpc::BindServiceMethod(typeof(HelloWorldService), "BindService")]
    public abstract partial class HelloWorldServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Protobufs.helloWorld.HelloWorldResponse> Say(global::Protobufs.helloWorld.HelloWorldRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for HelloWorldService</summary>
    public partial class HelloWorldServiceClient : grpc::ClientBase<HelloWorldServiceClient>
    {
      /// <summary>Creates a new client for HelloWorldService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public HelloWorldServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for HelloWorldService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public HelloWorldServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected HelloWorldServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected HelloWorldServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Protobufs.helloWorld.HelloWorldResponse Say(global::Protobufs.helloWorld.HelloWorldRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Say(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Protobufs.helloWorld.HelloWorldResponse Say(global::Protobufs.helloWorld.HelloWorldRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Say, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Protobufs.helloWorld.HelloWorldResponse> SayAsync(global::Protobufs.helloWorld.HelloWorldRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SayAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Protobufs.helloWorld.HelloWorldResponse> SayAsync(global::Protobufs.helloWorld.HelloWorldRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Say, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override HelloWorldServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new HelloWorldServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(HelloWorldServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Say, serviceImpl.Say).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, HelloWorldServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Say, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Protobufs.helloWorld.HelloWorldRequest, global::Protobufs.helloWorld.HelloWorldResponse>(serviceImpl.Say));
    }

  }
}
#endregion
