# 使用版本 3.3
version: '3.3'

#定義 volumes 的區塊，供 service 內指定容器使用
volumes:
    mongoData:

#定義 service 的區塊，一個 service 設定可以用來啟動多個容器
services:
    #定義啟動的容器名稱
    go_api:
        # 編譯檔來源
        build:
            context: ./api
            dockerfile: ./Dockerfile
        #輸出影像檔案名稱
        image: service/api_server
        container_name: GoAPI
        #等待指定container完成啟動 在運行
        depends_on:
            - go_db
            - go_redis
        #開放的 Port
        ports:
            - 1234:1234
        #環境變數
        environment:
            API_PORT: :1234
            SSL_CERTIFICATION: ./ssl/server.pem
            SSL_PRIVATE_KEY: ./ssl/server.key 
            JWT_SIGNING_KEY: SIGMA_SIGNING_KEY
            JWT_CLAIMS_KEY: JWT_CLAIMS
            DATABASE_USERNAME: root
            DATABASE_PASSWORD: 1111
            DATABASE_ADDRESS: go_db
            DATABASE_PORTS: 27017
            DATABASE_TABLE: main_db
            DATABASE_TIMEOUT: 5
            REDIS_CACHE_ADDRESS: go_redis
            REDIS_CACHE_PORT: 6379
            REDIS_CACHE_EXPIRATION: 600
        volumes:
            - ./ssl:/ssl
    #定義啟動的DB名稱
    go_db:
        #image 來源
        image: mongo
        container_name: GoDatabase
        ports:
            - 27017:27017
        volumes:
            - mongoData:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 1111         
    #定義啟動的Redis
    go_redis:
        image: redis
        container_name: GoRedis
        ports:
            - 37003:6379
    #定義啟動的File Server
    go_file:
        # 編譯檔來源
        build:
            context: ./file
            dockerfile: ./Dockerfile
        image: service/file_server
        container_name: GoFile
        ports:
            - 5678:5678
        #環境變數
        environment:
            FILE_PORT: :5678
        volumes:
            - ./bundles:/bundles
    #定義啟動的 Swagger-UI
    swagger_ui:
        image: swaggerapi/swagger-ui
        container_name: GoSwaggerUI
        ports:
            - 37004:8080
        volumes:
            - ./swagger/doc:/usr/share/nginx/html/doc
        environment:
            API_URL: doc/swagger.yaml
    #定義啟動的 mongo-express
    mongo_express:
        image: mongo-express
        container_name: GoMongoExpress
        ports:
            - 37005:8081
        environment:
            ME_CONFIG_MONGODB_SERVER: go_db
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: 1111
        depends_on:
            - go_db
        deploy:
            #定義重新啟動規則
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3                
    #定義啟動的 nginx
    nginx:
        image: nginx:stable-alpine
        container_name: GoNginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/logs:/var/log/nginx
            - ./ssl:/etc/nginx/cert
        depends_on:
            - swagger_ui
    #定義啟動的 gRPC
    go_grpc:
        # 編譯檔來源
        build:
            context: ./grpc
            dockerfile: ./Dockerfile
        #輸出影像檔案名稱
        image: service/grpc_server
        container_name: GoGRPC
        #開放的 Port
        ports:
            - 5033:5033
